#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class GallerySceneBuilder
{
    private const string ScenePath = "Assets/Scenes/Main.unity";
    private const string BuiltMarker = "Assets/Scenes/.gallery_scene_built";

    static GallerySceneBuilder()
    {
        EditorApplication.delayCall += BuildIfNeeded;
    }

    private static void BuildIfNeeded()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
            return;

        if (File.Exists(ScenePath) || File.Exists(BuiltMarker))
            return;

        Build();
    }

    [MenuItem("Gallery/Build Main Scene")]
    public static void Build()
    {
        Directory.CreateDirectory("Assets/Scenes");

        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        CreateGround();
        CreatePlayer();
        CreateGalleryPainting();
        CreateLight();

        EditorSceneManager.SaveScene(scene, ScenePath);
        EditorBuildSettings.scenes = new[]
        {
            new EditorBuildSettingsScene(ScenePath, true)
        };

        File.WriteAllText(BuiltMarker, "Generated by GallerySceneBuilder. Delete Main.unity and this marker to rebuild.");
        AssetDatabase.Refresh();

        Debug.Log("Gallery Main scene created successfully.");
    }

    private static void CreateGround()
    {
        GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Cube);
        ground.name = "Ground";
        ground.transform.position = new Vector3(0f, -0.5f, 0f);
        ground.transform.localScale = new Vector3(30f, 1f, 30f);
    }

    private static void CreatePlayer()
    {
        GameObject player = new GameObject("Player");
        player.transform.position = new Vector3(0f, 1.1f, -5f);

        CharacterController controller = player.AddComponent<CharacterController>();
        controller.height = 1.8f;
        controller.radius = 0.35f;
        controller.center = new Vector3(0f, 0.9f, 0f);
        controller.stepOffset = 0.3f;

        player.AddComponent<FirstPersonController>();

        GameObject cameraObject = new GameObject("PlayerCamera");
        cameraObject.transform.SetParent(player.transform, false);
        cameraObject.transform.localPosition = new Vector3(0f, 0.75f, 0f);
        cameraObject.transform.localRotation = Quaternion.identity;

        Camera camera = cameraObject.AddComponent<Camera>();
        camera.nearClipPlane = 0.01f;
        camera.farClipPlane = 1000f;
        camera.tag = "MainCamera";
        cameraObject.AddComponent<AudioListener>();

        FirstPersonController controllerScript = player.GetComponent<FirstPersonController>();
        SerializedObject serializedController = new SerializedObject(controllerScript);
        serializedController.FindProperty("cameraTransform").objectReferenceValue = cameraObject.transform;
        serializedController.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void CreateGalleryPainting()
    {
        GameObject painting = new GameObject("Gallery Painting");
        painting.transform.position = new Vector3(0f, 2.2f, 4f);
        painting.transform.rotation = Quaternion.Euler(0f, 180f, 0f);

        BoxCollider collider = painting.AddComponent<BoxCollider>();
        collider.size = new Vector3(2.6f, 2f, 0.12f);

        GameObject canvas = GameObject.CreatePrimitive(PrimitiveType.Cube);
        canvas.name = "Artwork";
        canvas.transform.SetParent(painting.transform, false);
        canvas.transform.localScale = new Vector3(2.35f, 1.75f, 0.06f);
        Object.DestroyImmediate(canvas.GetComponent<Collider>());

        Shader shader = Shader.Find("Universal Render Pipeline/Lit");
        if (shader == null) shader = Shader.Find("Standard");
        Material artworkMaterial = new Material(shader);
        artworkMaterial.color = new Color(0.12f, 0.32f, 0.55f, 1f);
        canvas.GetComponent<Renderer>().sharedMaterial = artworkMaterial;

        GameObject frame = GameObject.CreatePrimitive(PrimitiveType.Cube);
        frame.name = "Frame";
        frame.transform.SetParent(painting.transform, false);
        frame.transform.localPosition = new Vector3(0f, 0f, 0.045f);
        frame.transform.localScale = new Vector3(2.6f, 2f, 0.08f);
        Object.DestroyImmediate(frame.GetComponent<Collider>());

        Material frameMaterial = new Material(shader);
        frameMaterial.color = new Color(0.04f, 0.025f, 0.015f, 1f);
        frame.GetComponent<Renderer>().sharedMaterial = frameMaterial;

        GalleryPainting paintingScript = painting.AddComponent<GalleryPainting>();
        paintingScript.SetDisplayName("Mavi Galeri");
    }

    private static void CreateLight()
    {
        GameObject lightObject = new GameObject("Directional Light");
        Light light = lightObject.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1f;
        lightObject.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
    }
}
#endif