#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class GallerySceneBuilder
{
    private const string ScenePath = "Assets/Scenes/Main.unity";
    private const string BuiltMarker = "Assets/Scenes/.gallery_scene_built";

    static GallerySceneBuilder()
    {
        EditorApplication.delayCall += BuildIfNeeded;
    }

    private static void BuildIfNeeded()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
            return;

        if (File.Exists(ScenePath) || File.Exists(BuiltMarker))
            return;

        Build();
    }

    [MenuItem("Gallery/Build Main Scene")]
    public static void Build()
    {
        Directory.CreateDirectory("Assets/Scenes");

        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        CreateGround();
        CreatePlayer();
        CreateLight();

        EditorSceneManager.SaveScene(scene, ScenePath);
        EditorBuildSettings.scenes = new[]
        {
            new EditorBuildSettingsScene(ScenePath, true)
        };

        File.WriteAllText(BuiltMarker, "Generated by GallerySceneBuilder. Delete Main.unity and this marker to rebuild.");
        AssetDatabase.Refresh();

        Debug.Log("Gallery Main scene created successfully.");
    }

    private static void CreateGround()
    {
        GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Cube);
        ground.name = "Ground";
        ground.transform.position = new Vector3(0f, -0.5f, 0f);
        ground.transform.localScale = new Vector3(30f, 1f, 30f);
    }

    private static void CreatePlayer()
    {
        GameObject player = new GameObject("Player");
        player.transform.position = new Vector3(0f, 1.1f, -5f);

        CharacterController controller = player.AddComponent<CharacterController>();
        controller.height = 1.8f;
        controller.radius = 0.35f;
        controller.center = new Vector3(0f, 0.9f, 0f);
        controller.stepOffset = 0.3f;

        player.AddComponent<FirstPersonController>();

        GameObject cameraObject = new GameObject("PlayerCamera");
        cameraObject.transform.SetParent(player.transform, false);
        cameraObject.transform.localPosition = new Vector3(0f, 0.75f, 0f);
        cameraObject.transform.localRotation = Quaternion.identity;

        Camera camera = cameraObject.AddComponent<Camera>();
        camera.nearClipPlane = 0.01f;
        camera.farClipPlane = 1000f;
        camera.tag = "MainCamera";
        cameraObject.AddComponent<AudioListener>();

        FirstPersonController controllerScript = player.GetComponent<FirstPersonController>();
        SerializedObject serializedController = new SerializedObject(controllerScript);
        serializedController.FindProperty("cameraTransform").objectReferenceValue = cameraObject.transform;
        serializedController.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void CreateLight()
    {
        GameObject lightObject = new GameObject("Directional Light");
        Light light = lightObject.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1f;
        lightObject.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
    }
}
#endif