#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class GallerySceneBuilder
{
    private const string ScenePath = "Assets/Scenes/Main.unity";
    private const string BuiltMarker = "Assets/Scenes/.gallery_scene_built";

    static GallerySceneBuilder()
    {
        EditorApplication.delayCall += BuildIfNeeded;
    }

    private static void BuildIfNeeded()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
            return;

        if (File.Exists(ScenePath))
        {
            EnsurePaintingInScene();
            return;
        }

        if (File.Exists(BuiltMarker))
            return;

        Build();
    }

    [MenuItem("Gallery/Build Main Scene")]
    public static void Build()
    {
        Directory.CreateDirectory("Assets/Scenes");

        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        CreateGround();
        CreatePlayer();
        CreateGalleryPainting();
        CreateLight();

        EditorSceneManager.SaveScene(scene, ScenePath);
        EditorBuildSettings.scenes = new[]
        {
            new EditorBuildSettingsScene(ScenePath, true)
        };

        File.WriteAllText(BuiltMarker, "Generated by GallerySceneBuilder. Delete Main.unity and this marker to rebuild.");
        AssetDatabase.Refresh();

        Debug.Log("Gallery Main scene created successfully.");
    }

    private static void CreateGround()
    {
        GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Cube);
        ground.name = "Ground";
        ground.transform.position = new Vector3(0f, -0.5f, 0f);
        ground.transform.localScale = new Vector3(30f, 1f, 30f);
    }

    private static void CreatePlayer()
    {
        GameObject player = new GameObject("Player");
        player.transform.position = new Vector3(0f, 1.1f, -5f);

        CharacterController controller = player.AddComponent<CharacterController>();
        controller.height = 1.8f;
        controller.radius = 0.35f;
        controller.center = new Vector3(0f, 0.9f, 0f);
        controller.stepOffset = 0.3f;

        player.AddComponent<FirstPersonController>();

        GameObject cameraObject = new GameObject("PlayerCamera");
        cameraObject.transform.SetParent(player.transform, false);
        cameraObject.transform.localPosition = new Vector3(0f, 0.75f, 0f);
        cameraObject.transform.localRotation = Quaternion.identity;

        Camera camera = cameraObject.AddComponent<Camera>();
        camera.nearClipPlane = 0.01f;
        camera.farClipPlane = 1000f;
        camera.tag = "MainCamera";
        cameraObject.AddComponent<AudioListener>();

        FirstPersonController controllerScript = player.GetComponent<FirstPersonController>();
        SerializedObject serializedController = new SerializedObject(controllerScript);
        serializedController.FindProperty("cameraTransform").objectReferenceValue = cameraObject.transform;
        serializedController.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void CreateGalleryPainting()
    {
        GameObject painting = new GameObject("Gallery Painting");
        painting.transform.position = new Vector3(0f, 2.25f, 4f);
        painting.transform.rotation = Quaternion.Euler(0f, 180f, 0f);

        GalleryPainting paintingScript = painting.AddComponent<GalleryPainting>();
        paintingScript.SetDisplayName("Mavi Galeri");

        Shader shader = Shader.Find("Universal Render Pipeline/Lit");
        if (shader == null) shader = Shader.Find("Standard");

        CreatePanel(painting.transform, "Canvas", new Vector3(0f, 0f, 0f), new Vector3(2.35f, 1.7f, 0.10f), new Color(0.12f, 0.32f, 0.55f, 1f), shader);
        CreatePanel(painting.transform, "TopFrame", new Vector3(0f, 0.91f, -0.01f), new Vector3(2.75f, 0.16f, 0.22f), new Color(0.05f, 0.025f, 0.012f, 1f), shader);
        CreatePanel(painting.transform, "BottomFrame", new Vector3(0f, -0.91f, -0.01f), new Vector3(2.75f, 0.16f, 0.22f), new Color(0.05f, 0.025f, 0.012f, 1f), shader);
        CreatePanel(painting.transform, "LeftFrame", new Vector3(-1.295f, 0f, -0.01f), new Vector3(0.16f, 1.7f, 0.22f), new Color(0.05f, 0.025f, 0.012f, 1f), shader);
        CreatePanel(painting.transform, "RightFrame", new Vector3(1.295f, 0f, -0.01f), new Vector3(0.16f, 1.7f, 0.22f), new Color(0.05f, 0.025f, 0.012f, 1f), shader);

        CreatePanel(painting.transform, "InnerTop", new Vector3(0f, 0.76f, -0.065f), new Vector3(2.35f, 0.045f, 0.06f), new Color(0.8f, 0.55f, 0.18f, 1f), shader);
        CreatePanel(painting.transform, "InnerBottom", new Vector3(0f, -0.76f, -0.065f), new Vector3(2.35f, 0.045f, 0.06f), new Color(0.8f, 0.55f, 0.18f, 1f), shader);
        CreatePanel(painting.transform, "InnerLeft", new Vector3(-1.17f, 0f, -0.065f), new Vector3(0.045f, 1.48f, 0.06f), new Color(0.8f, 0.55f, 0.18f, 1f), shader);
        CreatePanel(painting.transform, "InnerRight", new Vector3(1.17f, 0f, -0.065f), new Vector3(0.045f, 1.48f, 0.06f), new Color(0.8f, 0.55f, 0.18f, 1f), shader);

        GameObject relief = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        relief.name = "ArtworkRelief";
        relief.transform.SetParent(painting.transform, false);
        relief.transform.localPosition = new Vector3(0f, 0f, -0.075f);
        relief.transform.localScale = new Vector3(1.1f, 0.72f, 0.12f);
        Object.DestroyImmediate(relief.GetComponent<Collider>());
        Material reliefMaterial = new Material(shader);
        reliefMaterial.color = new Color(0.9f, 0.45f, 0.18f, 1f);
        relief.GetComponent<Renderer>().sharedMaterial = reliefMaterial;
    }

    private static void CreatePanel(Transform parent, string name, Vector3 position, Vector3 scale, Color color, Shader shader)
    {
        GameObject panel = GameObject.CreatePrimitive(PrimitiveType.Cube);
        panel.name = name;
        panel.transform.SetParent(parent, false);
        panel.transform.localPosition = position;
        panel.transform.localScale = scale;
        Material material = new Material(shader);
        material.color = color;
        panel.GetComponent<Renderer>().sharedMaterial = material;
        Object.DestroyImmediate(panel.GetComponent<Collider>());
    }

    private static void EnsurePaintingInScene()
    {
        Scene scene = EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        if (GameObject.Find("Gallery Painting") != null)
            return;

        CreateGalleryPainting();
        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);
        AssetDatabase.SaveAssets();
        Debug.Log("Gallery painting added to the existing Main scene.");
    }

    private static void CreateLight()
    {
        GameObject lightObject = new GameObject("Directional Light");
        Light light = lightObject.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1f;
        lightObject.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
    }
}
#endif